// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SockerServer.Data.Context;

#nullable disable

namespace SockerServer.Data.Migrations
{
    [DbContext(typeof(SocketServerDbContext))]
    partial class SocketServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SockerServer.Data.Models.BuisnessField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BuisnessFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Informatique"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sante"
                        });
                });

            modelBuilder.Entity("SockerServer.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Etudiant"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Professeur"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Auxiliaire d’enseignement"
                        });
                });

            modelBuilder.Entity("SockerServer.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuisnessFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnRedList")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuisnessFieldId");

                    b.HasIndex("CategoryId");

                    b.ToTable("People");

                    b.HasDiscriminator<int>("CategoryId").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SockerServer.Data.Models.Student", b =>
                {
                    b.HasBaseType("SockerServer.Data.Models.Person");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuisnessFieldId = 1,
                            CategoryId = 0,
                            EmailAddress = "AAA",
                            FirstName = "AAA",
                            IsOnRedList = false,
                            LastName = "BBB",
                            Password = "1234",
                            ReferenceNumber = "AAAA"
                        },
                        new
                        {
                            Id = 2,
                            BuisnessFieldId = 1,
                            CategoryId = 0,
                            EmailAddress = "AA",
                            FirstName = "CCC",
                            IsOnRedList = true,
                            LastName = "BBB",
                            Password = "1234",
                            ReferenceNumber = "AAAA"
                        });
                });

            modelBuilder.Entity("SockerServer.Data.Models.Teacher", b =>
                {
                    b.HasBaseType("SockerServer.Data.Models.Person");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            BuisnessFieldId = 1,
                            CategoryId = 0,
                            EmailAddress = "AAA",
                            FirstName = "AAA",
                            IsOnRedList = false,
                            LastName = "BBB",
                            Password = "1234",
                            PhoneNumber = "AAAA"
                        },
                        new
                        {
                            Id = 4,
                            BuisnessFieldId = 1,
                            CategoryId = 0,
                            EmailAddress = "AA",
                            FirstName = "CCC",
                            IsOnRedList = true,
                            LastName = "BBB",
                            Password = "1234",
                            PhoneNumber = "AAAA"
                        });
                });

            modelBuilder.Entity("SockerServer.Data.Models.TeachingAssistant", b =>
                {
                    b.HasBaseType("SockerServer.Data.Models.Person");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.ToTable("People", t =>
                        {
                            t.Property("PhoneNumber")
                                .HasColumnName("TeachingAssistant_PhoneNumber");
                        });

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            Id = 5,
                            BuisnessFieldId = 1,
                            CategoryId = 0,
                            EmailAddress = "AAA",
                            FirstName = "AAA",
                            IsOnRedList = false,
                            LastName = "BBB",
                            Password = "1234",
                            PhoneNumber = "AAAA"
                        },
                        new
                        {
                            Id = 6,
                            BuisnessFieldId = 1,
                            CategoryId = 0,
                            EmailAddress = "AA",
                            FirstName = "CCC",
                            IsOnRedList = true,
                            LastName = "BBB",
                            Password = "1234",
                            PhoneNumber = "AAAA"
                        });
                });

            modelBuilder.Entity("SockerServer.Data.Models.Person", b =>
                {
                    b.HasOne("SockerServer.Data.Models.BuisnessField", "BuisnessField")
                        .WithMany()
                        .HasForeignKey("BuisnessFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SockerServer.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuisnessField");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
